-- Create the user_favorites table to store user collections
CREATE TABLE public.user_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  item_id TEXT NOT NULL,
  item_type TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now() at time zone 'utc'),

  -- A user should only be able to favorite a specific item once.
  CONSTRAINT user_favorites_unique_item UNIQUE (user_id, item_id, item_type)
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.user_favorites IS 'Stores the items (destinations, spots, routes, etc.) favorited by users.';
COMMENT ON COLUMN public.user_favorites.user_id IS 'The user who favorited the item.';
COMMENT ON COLUMN public.user_favorites.item_id IS 'The ID of the favorited item (e.g., a destination_id, spot_id).';
COMMENT ON COLUMN public.user_favorites.item_type IS 'The type of the favorited item (e.g., ''destination'', ''spot'', ''route'').';

-- Enable Row Level Security (RLS) for the table
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;
