// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Add a check to ensure the environment variables are loaded
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase URL or Anon Key is missing.");
  console.error("Please check your .env file and ensure it contains VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.");
  // Throwing an error stops the app from continuing with a broken configuration.
  throw new Error("Supabase configuration error: Environment variables not found.");
}


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // 禁用URL会话检测减少不必要的请求
  }
});